import { useMemo, useState } from "react";
import { z } from "zod";
import { CalendarPlus, Check } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { site } from "@/lib/site-content";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
const schema=z.object({appointment_type:z.enum(site.appointments),requested_date:z.string().date(),requested_time:z.string().regex(/^\d{2}:\d{2}$/),guest_name:z.string().trim().min(2).max(100),guest_email:z.string().trim().email().max(255),guest_phone:z.string().trim().max(40).optional(),notes:z.string().trim().max(1000).optional()});
export function AppointmentForm(){const [step,setStep]=useState(1);const [type,setType]=useState<(typeof site.appointments)[number]>(site.appointments[0]);const [date,setDate]=useState("");const [time,setTime]=useState("");const [details,setDetails]=useState({guest_name:"",guest_email:"",guest_phone:"",notes:""});const [status,setStatus]=useState<"idle"|"sending"|"sent"|"error">("idle");const min=useMemo(()=>{const d=new Date(Date.now()+site.booking.noticeHours*36e5);return d.toISOString().slice(0,10)},[]);const validDate=()=>{if(!date||!time)return false;const day=new Date(`${date}T12:00:00`).getDay();return site.booking.days.includes(day)};const submit=async()=>{const parsed=schema.safeParse({appointment_type:type,requested_date:date,requested_time:time,...details});if(!parsed.success){setStatus("error");return;}setStatus("sending");const {error}=await supabase.from("appointments").insert(parsed.data);setStatus(error?"error":"sent");if(!error)setStep(4)};const download=()=>{const start=new Date(`${date}T${time}:00`);const end=new Date(start.getTime()+site.booking.durationMinutes*60000);const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nDTSTART:${stamp(start)}\r\nDTEND:${stamp(end)}\r\nSUMMARY:HURRIAMO — ${type}\r\nDESCRIPTION:Appointment request awaiting confirmation.\r\nEND:VEVENT\r\nEND:VCALENDAR`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([ics],{type:"text/calendar"}));a.download="hurriamo-appointment.ics";a.click();URL.revokeObjectURL(a.href)};if(step===4)return <div className="border border-border p-8 md:p-12"><Check className="size-7 text-primary"/><h2 className="mt-7 font-display text-4xl">Your request is with the house.</h2><p className="mt-4 max-w-md text-muted-foreground">We will reply privately at {details.guest_email}. The requested time is not confirmed until you hear from us.</p><Button onClick={download} variant="outline" className="mt-8 rounded-none"><CalendarPlus/> Add request to calendar</Button></div>;
return <div><div className="mb-10 flex gap-3" aria-label={`Step ${step} of 3`}>{[1,2,3].map(n=><span key={n} className={`h-px flex-1 ${n<=step?"bg-primary":"bg-border"}`}/>)}</div>{step===1&&<div><p className="eyebrow">01 — Appointment</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{site.appointments.map(v=><Button key={v} type="button" variant={type===v?"default":"outline"} onClick={()=>setType(v)} className="h-20 whitespace-normal rounded-none px-5 text-left font-display text-lg">{v}</Button>)}</div><Button onClick={()=>setStep(2)} className="mt-8 h-12 rounded-none px-8">Continue</Button></div>}{step===2&&<div><p className="eyebrow">02 — Preferred time</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-xs uppercase tracking-[0.14em]">Date<Input className="mt-2" type="date" min={min} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="text-xs uppercase tracking-[0.14em]">Time<Input className="mt-2" type="time" min="10:00" max="18:00" value={time} onChange={e=>setTime(e.target.value)}/></label></div>{date&&!validDate()&&<p className="mt-3 text-sm text-destructive">Please choose Monday–Thursday or Saturday, with at least 48 hours’ notice.</p>}<div className="mt-8 flex gap-3"><Button variant="outline" onClick={()=>setStep(1)} className="rounded-none">Back</Button><Button disabled={!validDate()} onClick={()=>setStep(3)} className="rounded-none">Continue</Button></div></div>}{step===3&&<div><p className="eyebrow">03 — Your details</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Name"><Input value={details.guest_name} onChange={e=>setDetails({...details,guest_name:e.target.value})} maxLength={100}/></Field><Field label="Email"><Input type="email" value={details.guest_email} onChange={e=>setDetails({...details,guest_email:e.target.value})} maxLength={255}/></Field><Field label="Phone (optional)"><Input value={details.guest_phone} onChange={e=>setDetails({...details,guest_phone:e.target.value})} maxLength={40}/></Field><div className="sm:col-span-2"><Field label="A private note (optional)"><Textarea value={details.notes} onChange={e=>setDetails({...details,notes:e.target.value})} maxLength={1000}/></Field></div></div><div className="mt-8 border-y border-border py-5 text-sm"><p>{type}</p><p className="mt-1 text-muted-foreground">{date} at {time} · {site.booking.durationMinutes} minutes</p></div><div className="mt-8 flex gap-3"><Button variant="outline" onClick={()=>setStep(2)} className="rounded-none">Back</Button><Button onClick={submit} disabled={status==="sending"} className="rounded-none">{status==="sending"?"Sending…":"Request appointment"}</Button></div>{status==="error"&&<p className="mt-4 text-sm text-destructive">Please check your details and try again.</p>}</div>}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs uppercase tracking-[0.14em]"><span className="mb-2 block">{label}</span>{children}</label>}
