import { useState } from "react";
import { z } from "zod";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
const schema=z.object({sender_name:z.string().trim().min(2).max(100),sender_email:z.string().trim().email().max(255),subject:z.string().trim().min(2).max(120),message:z.string().trim().min(10).max(1500)});
export function ContactForm(){const [state,setState]=useState<"idle"|"sending"|"sent"|"error">("idle");const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setState("sending");const f=new FormData(e.currentTarget);const parsed=schema.safeParse(Object.fromEntries(f));if(!parsed.success){setState("error");return;}const {error}=await supabase.from("contact_requests").insert(parsed.data);setState(error?"error":"sent");if(!error)e.currentTarget.reset();};return <form onSubmit={submit} className="space-y-5" noValidate><Field label="Name"><Input name="sender_name" required maxLength={100}/></Field><Field label="Email"><Input name="sender_email" type="email" required maxLength={255}/></Field><Field label="Subject"><Input name="subject" required maxLength={120}/></Field><Field label="Message"><Textarea name="message" required minLength={10} maxLength={1500} className="min-h-36 resize-y"/></Field><Button type="submit" disabled={state==="sending"} className="h-12 w-full rounded-none uppercase tracking-[0.14em]">{state==="sending"?"Sending…":"Send private enquiry"}</Button><p aria-live="polite" className={`text-sm ${state==="error"?"text-destructive":"text-muted-foreground"}`}>{state==="sent"?"Your private enquiry has been received.":state==="error"?"Please review each field and try again.":""}</p></form>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs uppercase tracking-[0.14em]"><span className="mb-2 block">{label}</span>{children}</label>}
