/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as HouseRouteImport } from './routes/house'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/director': typeof DirectorRoute
  '/house': typeof HouseRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/director': typeof DirectorRoute
  '/house': typeof HouseRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/director': typeof DirectorRoute
  '/house': typeof HouseRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointment'
    | '/contact'
    | '/director'
    | '/house'
    | '/portfolio'
    | '/process'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointment'
    | '/contact'
    | '/director'
    | '/house'
    | '/portfolio'
    | '/process'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/appointment'
    | '/contact'
    | '/director'
    | '/house'
    | '/portfolio'
    | '/process'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentRoute: typeof AppointmentRoute
  ContactRoute: typeof ContactRoute
  DirectorRoute: typeof DirectorRoute
  HouseRoute: typeof HouseRoute
  PortfolioRoute: typeof PortfolioRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentRoute: AppointmentRoute,
  ContactRoute: ContactRoute,
  DirectorRoute: DirectorRoute,
  HouseRoute: HouseRoute,
  PortfolioRoute: PortfolioRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
